
# This file lists Edge Functions that should be built along with the database.
# When this file is present, the CLI will look for each Edge Function's entrypoint in 
# the ./functions/<name>/index.ts or ./functions/<name>/index.js file.

[config]
# Base directory containing edge functions
base_dir = "functions"

# Run these after creating or updating any edge function
post_build = ["npx", "supabase", "functions", "deploy", "--no-verify-jwt"]

# List of functions to include when building
[[functions]]
# Functions will be deployed to Supabase Edge Functions
name = "port-data"
verify_jwt = false

[[functions]]
name = "process-file-upload"
verify_jwt = false

[[functions]]
name = "hello-world"
verify_jwt = false

[[functions]]
name = "analyze-data-insights"
verify_jwt = false

[[functions]]
name = "analyze-data-integrity"
verify_jwt = false

[[functions]]
name = "analyze-data-quality"
verify_jwt = false

[[functions]]
name = "analyze-data-statistics"
verify_jwt = false

[[functions]]
name = "analyze-file"
verify_jwt = false

[[functions]]
name = "analyze-table-context"
verify_jwt = false

[[functions]]
name = "apply-data-fix"
verify_jwt = false

[[functions]]
name = "chat-with-dona"
verify_jwt = false

[[functions]]
name = "create-data-table"
verify_jwt = false

[[functions]]
name = "generate-visualizations"
verify_jwt = false

[[functions]]
name = "get-google-maps-key"
verify_jwt = false

[[functions]]
name = "google-business-oauth"
verify_jwt = false

[[functions]]
name = "read-file-data"
verify_jwt = false

[[functions]]
name = "suggest-column-names"
verify_jwt = false
