
project_id = "zzmezxjwhtiwhnhqvnck"

[config]
# Base directory containing edge functions
base_dir = "functions"

# Lista das funções essenciais para manter
[[functions]]
name = "process-file-upload"
verify_jwt = false

[[functions]]
name = "get-google-maps-key"
verify_jwt = false

[[functions]]
name = "google-business-oauth"
verify_jwt = false

[[functions]]
name = "chat-with-dona"
verify_jwt = false

[[functions]]
name = "analyze-data-insights"
verify_jwt = false

[[functions]]
name = "process-invite"
verify_jwt = false

[[functions]]
name = "read-file-data"
verify_jwt = false

[[functions]]
name = "create-airbyte-user"
verify_jwt = false

[[functions]]
name = "analyze-table-context"
verify_jwt = false

# Nova função para gerenciar insights
[[functions]]
name = "manage-insights"
verify_jwt = false
